spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/drone
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  output:
    ansi:
      enabled: always
  liquibase:
    enabled: true
  jmx:
    enabled: true
  jpa:
    hibernate:
      ddl-auto: none
      show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  file:
    path: logs/spring-boot-application.log
  pattern:
    file: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID}){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
server:
  port: 8080